# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: sample_app_development
  username: postgres
  password: xcrash
  host: localhost 
  
test:
  adapter: postgresql
  database: sample_app_development
  username: postgres
  password: xcrash
  host: localhost 

production:
  adapter: postgresql
  database: sample_app_development
  username: postgres
  password: xcrash
  host: localhost 